Repository explosion/thinc, pull requests merged in 2020-11, with the labels that each got.

#412 Fix random seed for pytorch
  thinc/util.py
Labels: enhancement, interop / pytorch

#405 check dims before calling blis.gemm
  thinc/backends/numpy_ops.pyx
Labels: feat / ux

#407 Remove StaticVectors + dropout fix
  thinc/api.py
  thinc/layers/__init__.py
  thinc/layers/embed.py
  thinc/layers/hashembed.py
  thinc/layers/staticvectors.py
  thinc/tests/layers/test_layers_api.py
Labels: bug, enhancement, feat / layers, tests

#421 Fix finalization method name for Beam
  thinc/extra/search.pyx
Labels: bug

#422 Fix finalization method name for Beam
  thinc/extra/search.pyx
Labels: bug
