Repository explosion/thinc, pull requests merged in 2021-09, with the labels that each got.

#530 Add wrap_model_recursive
  thinc/api.py
  thinc/model.py
  thinc/tests/model/test_model.py
Labels: enhancement

#529 PyTorchShim: add support for mixed-precision
  thinc/api.py
  thinc/layers/pytorchwrapper.py
  thinc/shims/__init__.py
  thinc/shims/pytorch.py
  thinc/shims/pytorch_grad_scaler.py
  thinc/tests/shims/__init__.py
  thinc/tests/shims/pytorch_grad_scaler.py
  thinc/util.py
Labels: enhancement, feat / shims, interop / pytorch

#527 Allow config overrides to add new keys
  thinc/about.py
  thinc/config.py
  thinc/tests/test_config.py
Labels: enhancement, feat / config

#533 Fix default ops for get_array_ops
  thinc/backends/__init__.py
Labels: bug, feat / ops

#532 Speed up clip_gradient with GPU training
  thinc/backends/cupy_ops.py
Labels: enhancement, performance

#535 Improve wrapping in with_{debug,nvtx_range}
  thinc/layers/with_debug.py
  thinc/layers/with_nvtx_range.py
  thinc/model.py
  thinc/tests/model/test_model.py
Labels: enhancement, feat / layers

#536 CategoricalCrossEntropy: support missing values for int arrays
  thinc/loss.py
  thinc/tests/test_loss.py
Labels: enhancement, feat / ops

#537 Fix replace_node on nodes with indirect node refs
  thinc/model.py
  thinc/tests/model/test_model.py
Labels: bug
