Repository explosion/thinc, pull requests merged in 2022-11, with the labels that each got.

#754 Add `SparseLinear_v2`, fixing indexing issues
  thinc/api.py
  thinc/layers/__init__.py
  thinc/layers/sparselinear.pyx
  thinc/tests/layers/test_layers_api.py
  thinc/tests/layers/test_sparse_linear.py
  website/docs/api-layers.md
Labels: bug, feat / layers

#802 Add TorchScriptWrapper_v1
  thinc/api.py
  thinc/layers/__init__.py
  thinc/layers/torchscriptwrapper.py
  thinc/shims/__init__.py
  thinc/shims/torchscript.py
  thinc/tests/layers/test_torchscriptwrapper.py
  website/docs/api-layers.md
  website/docs/api-model.md
  website/docs/usage-frameworks.md
Labels: enhancement, interop / pytorch, serialization

#807 Correct sequence length errors for reduce_first/last
  thinc/backends/ops.py
  thinc/tests/backends/test_ops.py
Labels: bug, feat / ux
