Repository explosion/thinc, pull requests merged in 2023-01, with the labels that each got.

#834 Fix cython directive `language_level`
  setup.py
Labels: bug

#832 Add pull request and bug report templates
  .github/ISSUE_TEMPLATE/01_bugs.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#833 Fix required maximum version of typing-extensions
  requirements.txt
  setup.cfg
Labels: install

#836 Update dev requirements for pytest-cov and coverage
  requirements.txt
Labels: tests

#837 Add `Schedule.to_generator`
  thinc/schedules.py
  thinc/tests/test_schedules.py
  website/docs/api-schedules.md
Labels: enhancement, 🔜 v9.0

#842 Add plateau.v1 schedule
  thinc/api.py
  thinc/schedules.py
  thinc/tests/test_schedules.py
  website/docs/api-schedules.md
Labels: enhancement, feat / optimizers

#844 Update Dockerfile
  website/.dockerignore
  website/Dockerfile
  website/README.md
Labels: docs
